
VERSION: '1.0'

ANIMATION:
    SELECTION: ARROW

PREFIX:
    GENERAL: '&6&lWolfo &7&l» &r'
    TITLE: '&7» &6&lWolfo'


# List of cosmetics and their effects
# Personalize cosmetics with this example:
#   - {SKDRAGON EFFECT};{GUI MATERIAL};{GUI NAME}

COSMETICS:
    PARTICLE:
    - explosion;bone meal;&7Explosion
    - firework;firework;&fTraînée de feu d'artifice
    - crit;trident;&3Coup critique
    - critmagic;trident of sharpness 1;&3Coup critique magique
    - smoke;campfire;&8Fumée
    - angryvillager;baked potato;&cColère
    - happyvillager;potato;&aJoyeux
    - waterdrip;water bucket;&bGouttes d'eau
    - flame;flint and steel;&eFlammes
    - lavadrip;lava bucket;&6Gouttes de lave
    - note;note block; &6Note
    - portal;ender eye;&dPortail
    - enchantmenttable;enchanting table;&cEnchantement
    - cloud;nether star;&fNuage
    - snowball;snowball;&fNeige
    - slime;slimeball;&aSlime
    - heart;apple;&cCœur
    EFFECT:
    - wings;elytra;&dÉlytres
    - nyancat;dirt;&dN&ey&aa&6n&d c&aa&dt
    - rings;string;&6Anneaux
    - spiral;lead;&eSpirale

PERMISSION:
    ADMIN: lg.admin

MESSAGE:
    JOIN_INFO: '&fSi tu ne connais pas (encore !) les règles du jeu, rends-toi dans les informations afin d''en savoir plus.'
    HELLO: '&7Bonjour !'
    START_PREPARE: '&fPréparez vos stratégies, le jeu va commencer ...'
    START_ROLES: '&fWow ! On est sur le point de commencer, quel rôle allez-vous avoir ?'
    COSM_ON: '&fNous avons activé tes particules, j''espère qu''elles te vont bien.'
    COSM_OFF: 'Oh non ... Déjà ? Si tu veux les réactiver, rendez-vous dans les cosmétiques.'
    SUCCESS_LOADING: '&aThe config has been loaded without errors. '
    PERMISSION: '&cVous n''avez pas accès à cette commande.'
    SETWAITROOM: '&eVous avez correctement défini la salle d''attente à votre position.'
    SETDEATHROOM: '&eVous avez correctement défini la zone des morts à votre position.'
    ADDSPAWN: '&eVous avez correctement défini la position de spawn à votre position. '
    FORCESTART: '&eVous avez correctement démarré la partie de force.'
    FORCESTOP: '&eVous avez correctement arrêté la partie de force.'
    DEBUGON: '&eVous avez correctement &aactivé &ele mode développement.'
    DEBUGOFF: '&eVous avez correctement &cdésactivé &ele mode développement.'
    YMLON: '&eVous avez correctement &aactivé &eles informations YML.'
    YMLOFF: '&eVous avez correctement &cdésactivé &eles informations YML.'
    SETUP: '&eVous avez correctement mis en place la partie de LG.'
    SETUPERROR: '&cVous avez déjà effectué cette commande.'
    ALREADYSTART: '&cLa partie est déjà en cours.'
    ALREADYSTOP: '&cLa partie est déjà arrêtée.'
    ALREADYSETUP: '&cLa partie est déjà configurée.'
    ENDGAME: La partie est terminée.
    ROLEDESC: '&eDescription de votre rôle :'
    MUTED: Votre rôle ne vous permet pas parler durant la nuit.
    GOODLEFT: Vous avez correctement quitté la partie.
    NOTENOUGH1: '&cIl manque '
    NOTENOUGH2: ' &cjoueurs avant de lancer une partie.'
    TOOMANY: '&cIl y a trop de joueurs pour lancer une partie.'
    REVEAL: 'Vous êtes désormais '
    START: '&6➥ &eLa partie commence !'
    STARTING: '&6➥ &eLa partie commence dans '
    YMLRELOAD: '&eEtes-vous sûr de vouloir réinitialiser les messages ? Si oui, faites
        /lg ymlreload confirm.'
    VICTORY_FIRST: '&aConditions de victoire :'
    VICTORY:
    - '  &f» &eTous les &6villagoies &esont mort'
    - '  &f» &eTous les &6Loup-garou sont &emort'
    - '  &f» &eLe &6Fou &eest tué par le village'
    - '  &f» &eLa cible du &6chasseur de tête &eest tué par le village'
    - '  &f» &eLes &6deux amants &eainsi que &6cupidon &esont les trois derniers survivant'
    - ''
    ADMIN_FIRST: '&eCommandes admin :'
    ADMIN:
    - '  &f» &e/wolfo help'
    - '  &f» &e/wolfo setwait'
    - '  &f» &e/wolfo setdeath'
    - '  &f» &e/wolfo addSpawn'
    - '  &f» &e/wolfo forcestart'
    - '  &f» &e/wolfo forcestop'
    - ''
    AUTO:
    - Vous pouvez personnaliser la particule ainsi que l'effet de vos cosmétiques
        !
    - La partie peut commencer dès lorsque 5 joueurs auront rejoint la partie.

GUI:
    INFO_TITLE: '&8➽ &dInformations du LG'
    ROLELIST: '&8» &6Liste des rôles'
    ROLELIST_TITLE: '&8➽ &6Liste des rôles'
    RULES: '&8» &bRègles du jeu'
    VICTORY: '&8» &aCondition de victoire'
    PARTICLE_SELECT: '&8➽ &6Choix de la particule'
    EFFECT_SELECT: '&8➽ &6Choix de l''effet'

ITEM:
    COSM: '&8➽ &bCosmétiques &7(clic-droit)'
    COSM_OFF: '&8➽ &cDésactiver k''effet cosmétique &7(clic-droit)'
    INFO: '&8➽ &dInformations &7(clic-droit)'
    EXIT: '&8➽ &cQuitter la partie &7(clic-droit)'

TIME:
    HOUR: heure(s)
    SECOND: seconde(s)

WEREWOLF:
    NAME: '&cLoup-Garou'
    DESC: '&8➥ &7Chaque nuit, vous devez voter pour l''élimination d''un joueur. &7Votre
        but est d''éliminer tous les villageois.'
    HEAD: '{SkullOwner:{Id:"9cd0e1fb-c1d6-4859-9392-13655a000118",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzY4ZDQzMTI5MzliYjMxMTFmYWUyOGQ2NWQ5YTMxZTc3N2Y4ZjJjOWZjNDI3NTAxY2RhOGZmZTNiMzY3NjU4In19fQ=="}]}}}'

WEREWOLF_ALPHA:
    NAME: '&4Loup-Garou Alpha'
    DESC: Votre vote &ecompte double&7.
    HEAD: '{SkullOwner:{Id:"736e9be2-4984-4cbc-bbb6-9ab419bb55bc",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjgzYTJhYTlkMzczNGI5MTlhYzI0Yzk2NTllNWUwZjg2ZWNhZmJmNjRkNDc4OGNmYTQzM2JiZWMxODllOCJ9fX0="}]}}}'

TOWNSFOLK_CURSED:
    NAME: '&7Villageois &8Maudit'
    DESC: '&8➥ &7Vous êtes un villageois normal, vous n''avez rien à faire. &7En revanche,
        si les Loup-Garous vous tue, vous &edeviendrez Loup-Garou&7.'

TOWNSFOLK:
    NAME: '&7Villageois'
    DESC: '&8➥ &7Vous n''avez aucune action spécifique, vous n''avez &eaucune faculté&7.'

CUPID:
    NAME: '&dCupidon'
    DESC: '&8➥ &7Au début de la partie, vous devez sélectionnez deux joueurs qui seront
        &eamant &7durant toute la partie. Si l''un des deux meurt, l''autre mourra
        également.'
    HEAD: '{SkullOwner:{Id:"94c9b15f-f65a-427d-a699-ad0d4d5489f6",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjRlYWY4OTQyOGEzNjQ5YzI2ZWRjMWY3MWNjMTlmMjYzZTlmNGViMzFlZDE4Yzk3Njg2YWFjODJmNzY0MjQyIn19fQ=="}]}}}'

SEER:
    NAME: '&aVoyante'
    DESC: '&8➥ &7Chaque nuit, vous avez la possiblité de &econnaître le rôle d''un
        joueur&7.'

SEER_AURA:
    NAME: '&2Voyante Aura'
    DESC: '&8➥ &7Chaque nuit, vous avez la possiblité de &econnaître l''aura d''un
        joueur&7. L''aura peut être "Claire", "Obscure" ou bien "Inconnue".'

CRAZY:
    NAME: '&6Fou'
    DESC: '&8➥ &7Vous devez essayer de convaincre le &evillage de vous tuer&7. Si
        vous y arrivez, vous gagnerez la partie, mais pensez à être malin ;)'
    HEAD: '{SkullOwner:{Id:"7e18508f-feb6-445b-8020-2c7cb79ace7c",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzFiZWNhY2VjODU4YTE5ODQ4ODYwYjI1MjJjMzI5MzZhZGYxNTg4YzFlZjQyMzc5NDAzZmVmODNkYTRiYiJ9fX0="}]}}}'

SHOOTER:
    NAME: '&eTireur'
    DESC: '&8➥ &7Vous commencez la partie avec &edeux balles&7. Vous aurez la possiblité
        de tuer n''importe qui.'

HEADHUNTER:
    NAME: '&9Chasseur de Tête'
    DESC: '&8➥ &7Au début de la partie, un joueur sera choisi aléatoirement. Si ce
        joueur est &etué par le village&7, il gagnera la partie.'
    HEAD: '{SkullOwner:{Id:"9d58f311-003b-4d1d-8ba8-b678e182bab3",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2MxZGYwZGI4ZDQ3NzNjYzI1NWE2M2I4ZjBiMGU0Y2RkN2Q3NGMzYjRjNjc1MzYyMTY4NDYwYmM2N2JiMzAyZSJ9fX0="}]}}}'

DOCTOR:
    NAME: '&bDocteur'
    DESC: '&8➥ &7Vous avez la possiblité chaque nuit de &eprotéger une personne contre
        les Loup-Garous.'

WITCH:
    NAME: '&5Sorcière'
    DESC: '&8➥ &7Vous possédez &edeux potions&7. L''une permets de récussiter un joueur,
        l''autre permets de tuer un joueur. Vous ne pouvez les utiliser qu''une seule
        fois.'
    HEAD: '{SkullOwner:{Id:"7f92b3d6-5ee0-4ab6-afae-2206b9514a63",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjBlMTNkMTg0NzRmYzk0ZWQ1NWFlYjcwNjk1NjZlNDY4N2Q3NzNkYWMxNmY0YzNmODcyMmZjOTViZjlmMmRmYSJ9fX0="}]}}}'

TEAM:
    WEREWOLF: '&cLoup-Garou'
    TOWNSFLOK: '&6Village'
    WW_TF: '&6Village &8| &cLoup-Garou'
    SOLO: '&aSolo'