VERSION: '1.0'

ANIMATION:
    SELECTION: ARROW

PREFIX:
    GENERAL: '&6&lWolfo &7&l» &r'
    TITLE: '&7» &6&lWolfo'

COSMETICS:
    PARTICLE:
    - explosion;bone meal;&7Explosion
    - firework;firework;&9Feu d'artifice
    - crit;trident;&3Coup critique
    - critmagic;trident of sharpness 1;&3Coup critique magique
    - smoke;campfire;&8Fumée
    - angryvillager;baked potato;&cColère
    - happyvillager;potato;&aJoyeux
    - waterdrip;water bucket;&bGouttes d'eau
    - flame;flint and steel;&eFlammes
    - lavadrip;lava bucket;&6Gouttes de lave
    - note;note block;&6Note
    - portal;ender eye;&dPortail
    - enchantmenttable;enchanting table;&cEnchantement
    - cloud;nether star;&fNuage
    - snowball;snowball;&fNeige
    - slime;slimeball;&aSlime
    - heart;apple;&cCœur
    EFFECT:
    - wings;elytra;&dÉlytres
    - nyancat;dirt;&dN&ey&aa&6n &cc&aa&dt
    - rings;string;&6Anneaux
    - spiral;lead;&eSpirale

PERMISSION:
    ADMIN: lg.admin
    MESSAGE: '&cVous n''avez pas les privilèges d''exécuter cette action.'

MESSAGE:
    START:
        PREPARE: '&fPréparez vos stratégies, le jeu va commencer ...'
        ROLES: '&fWow ! On est sur le point de commencer, quel rôle allez-vous avoir
            ?'
        BEGIN: '&6➥ &eLa partie commence dans '
        START: '&6➥ &eLa partie commence !'
    COSMETICS:
        ON1: '&fNous avons activé tes particules, j''espère que tes '
        ON2: '&fte vont bien ! :D'
        'false': Oh non ... Déjà ? Si tu veux les réactiver, rendez-vous dans les
            cosmétiques.
    PRIVACY:
        CLOSED: '&fLes opérateurs ont &cfermé&f cette partie.'
        WHITELISTED: '&fLes opérateurs ont &6réservé&f cette partie à certains joueurs. '
        OPEN: '&fLes opérateurs ont &aouvert&f cette partie à tous les joueurs. '
    TIME:
        WAIT: '&7Attente'
        START: '&aDémarrage'
        DAY: '&eJour'
        NIGHT: '&9Nuit'
        VOTE: '&dVote'
    GAMETYPE:
        '0': '&7Attente ...'
        '1': '&aMini!'
        '2': '&eClassik!'
        '3': '&6Ultimate!'
        '4': '&cTrop de joueurs!'
    WELCOME: '&7Bienvenue ! Si tu ne connais pas les règles du jeu, rends-toi dans
        les informations !'
    SUCCESS_LOADING: '&aWolfo seems to have started correctly. '
    FORCESTART: '&eVous avez correctement démarré la partie de force.'
    FORCESTOP: '&eVous avez correctement arrêté la partie de force.'
    SETUPERROR: '&cVous avez déjà effectué cette commande.'
    ALREADYSTART: '&cLa partie est déjà en cours.'
    JOINED: '&fa &arejoint&f la partie.'
    LEFT: '&fa &cquitté&f la partie.'
    WHITELISTED_SUCCESS: '&fL''accès au serveur de ce joueur a été &aautorisé&f. Super
        !'
    WHITELISTED_ALREADY: '&fL''accès au serveur de ce joueur est déjà &aautorisé&f.'
    NOT_WHITELISTED_SUCCESS: '&fL''accès au serveur de ce joueur a été &crévoqué&f.
        Dommage pour lui.'
    NOT_WHITELISTED_ALREADY: '&fL''accès au serveur de ce joueur est déjà &crévoqué&f.'
    WHITELISTED: '&fCe joueur est &aautorisé&f à jouer sur ce serveur.'
    NOT_WHITELISTED: '&fCe joueur &cn''est pas autorisé&f à jouer sur ce serveur. '
    ALREADYSTOP: '&cLa partie est déjà arrêtée.'
    ALREADYSETUP: '&cLa partie est déjà configurée.'
    ENDGAME: La partie est terminée.
    ROLEDESC: '&eDescription de votre rôle :'
    MUTED: Votre rôle ne vous permet pas parler durant la nuit.
    GOODLEFT: Vous partez déjà ? On s'amuse tout de suite moins sans vous.
    NOTENOUGH1: '&cIl manque '
    NOTENOUGH2: ' &cjoueurs avant de lancer une partie.'
    NOTENOUGH: '&fIl n''y a &cpas assez de joueur&f pour lancer une partie. Si vous
        avez des amis, invitez-les et réessayez.'
    TOOMANY: '&fWow! Il y a beaucoup de monde, vous &cne pouvez pas&f rejoindre cette
        partie.'
    REVEAL: 'Vous êtes désormais '
    VICTORY:
        TITLE: '&fVoici les conditions de victoire :'
        MSG:
        - ''
        - '  &f» &eTous les &6villagoies &esont mort'
        - '  &f» &eTous les &6Loup-garou sont &emort'
        - '  &f» &eLe &6Fou &eest tué par le village'
        - '  &f» &eLa cible du &6chasseur de tête &eest tué par le village'
        - '  &f» &eLes &6deux amants &eainsi que &6cupidon &esont les trois derniers
            survivant'
        - ''
    COMMANDS:
        TITLE: '&fVoici la liste des commandes :'
        MSG:
        - ''
        - '  &f» &e/wolfo help&7: affiche cette page d''aide'
        - '  &f» &e/wolfo admin&7: administration de la partie &c*'
        - '  &f» &e/wolfo manage&7: gestion de la partie &c*'
        - '  &f» &e/wolfo my&7: affiche vos informations'
        - ''

GUI:
    ROLELIST: '&8➽ &6Liste des rôles'
    PARTICLE_SELECT: '&8➽ &6Choix de la particule'
    EFFECT_SELECT: '&8➽ &6Choix de l''effet'
    SETUP: '&8➽ &6Configuration de &6Wolfo'
    MANAGE: '&8➽ &6Gestion de &6Wolfo'

ITEM:
    COSM: '&8➽ &bCosmétiques &7(clic-droit)'
    COSM_OFF: '&8➽ &cDésactiver l''effet cosmétique &7(clic-droit)'
    INFO: '&8➽ &dInformations &7(clic-droit)'
    EXIT: '&8➽ &cQuitter la partie &7(clic-droit)'
    SETUP: '&8➽ &6Configurer la partie &c(opérateur)'
    MANAGE: '&8➽ &5Gérer la partie &c(opérateur)'

TIME:
    HOUR: heure(s)
    SECOND: seconde(s)

ROLES:
    WEREWOLF:
        NAME: '&cLoup-Garou'
        DESC:
        - ''
        - '&8➥ &7Chaque nuit, vous devez voter pour l''élimination d''un joueur.'
        - '&7Votre but est d''éliminer tous les villageois.'
        - ''
        - '&8➥ &7Votre équipe: &cLoup-Garou'
        ITEM: player head
        NBT: '{SkullOwner:{Id:"9cd0e1fb-c1d6-4859-9392-13655a000118",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzY4ZDQzMTI5MzliYjMxMTFmYWUyOGQ2NWQ5YTMxZTc3N2Y4ZjJjOWZjNDI3NTAxY2RhOGZmZTNiMzY3NjU4In19fQ=="}]}}}'
    WEREWOLF_ALPHA:
        NAME: '&cLoup-Garou &4Alpha'
        DESC:
        - ''
        - '&8➥ &7Chaque nuit, vous devez voter pour l''élimination d''un joueur.'
        - '&7Votre but est d''éliminer tous les villageois. Votre vote compte double.'
        - ''
        - '&8➥ &7Votre équipe: &cLoup-Garou'
        ITEM: player head
        NBT: '{SkullOwner:{Id:"736e9be2-4984-4cbc-bbb6-9ab419bb55bc",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjgzYTJhYTlkMzczNGI5MTlhYzI0Yzk2NTllNWUwZjg2ZWNhZmJmNjRkNDc4OGNmYTQzM2JiZWMxODllOCJ9fX0="}]}}}'
    TOWNSFOLK_CURSED:
        NAME: '&7Villageois &8Maudit'
        DESC:
        - ''
        - '&8➥ &7Vous êtes un villageois normal, vous n''avez rien à faire.'
        - '&7En revanche, si les Loup-Garous vous tue, vous &edeviendrez Loup-Garou&7.'
        - ''
        - '&8➥ &7Votre équipe: &6Village &f| &cLoup-Garou'
        ITEM: bread
    TOWNSFOLK:
        NAME: '&7Villageois'
        DESC:
        - ''
        - '&8➥ &7Vous n''avez aucune action spécifique, vous n''avez &eaucune faculté&7.'
        - ''
        - '&8➥ &7Votre équipe: &6Village'
        ITEM: bread
    CUPID:
        NAME: '&dCupidon'
        DESC:
        - ''
        - '&8➥ &7Au début de la partie, vous devez sélectionnez deux joueurs qui seront'
        - '&eamant &7durant toute la partie. Si l''un des deux meurt, l''autre mourra
            également.'
        - ''
        - '&8➥ &7Votre équipe: &6Village'
        ITEM: player head
        NBT: '{SkullOwner:{Id:"94c9b15f-f65a-427d-a699-ad0d4d5489f6",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjRlYWY4OTQyOGEzNjQ5YzI2ZWRjMWY3MWNjMTlmMjYzZTlmNGViMzFlZDE4Yzk3Njg2YWFjODJmNzY0MjQyIn19fQ=="}]}}}'
    SEER:
        NAME: '&aVoyante'
        DESC:
        - ''
        - '&8➥ &7Chaque nuit, vous avez la possiblité de &econnaître le rôle d''un
            joueur&7.'
        - ''
        - '&8➥ &7Votre équipe: &6Village'
        ITEM: eyes of ender
    SEER_AURA:
        NAME: '&2Voyante Aura'
        DESC:
        - ''
        - '&8➥ &7Chaque nuit, vous avez la possiblité de &econnaître l''aura d''un
            joueur&7.'
        - '&7L''aura peut être &aClaire&7, &8Obscure &7ou bien &9Inconnue&7.'
        - ''
        - '&8➥ &7Votre équipe: &6Village'
        ITEM: ender pearl
    CRAZY:
        NAME: '&6Fou'
        DESC:
        - ''
        - '&8➥ &7Vous devez essayer de convaincre le &evillage de vous tuer&7.'
        - '&7Si vous y arrivez, vous gagnerez la partie, mais pensez à être malin
            ;)'
        - ''
        - '&8➥ &7Votre équipe: &aSolo'
        ITEM: player head
        NBT: '{SkullOwner:{Id:"7e18508f-feb6-445b-8020-2c7cb79ace7c",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzFiZWNhY2VjODU4YTE5ODQ4ODYwYjI1MjJjMzI5MzZhZGYxNTg4YzFlZjQyMzc5NDAzZmVmODNkYTRiYiJ9fX0="}]}}}'
    SHOOTER:
        NAME: '&eTireur'
        DESC:
        - ''
        - '&8➥ &7Vous commencez la partie avec &edeux balles&7.'
        - '&7Vous aurez la possiblité de tuer n''importe qui.'
        - ''
        - '&8➥ &7Votre équipe: &6Village'
        ITEM: bow
    HEADHUNTER:
        NAME: '&9Chasseur de Tête'
        DESC:
        - ''
        - '&8➥ &7Au début de la partie, un joueur sera choisi aléatoirement.'
        - '&7Si ce joueur est &etué par le village&7, il gagnera la partie.'
        - ''
        - '&8➥ &7Votre équipe: &aSolo'
        ITEM: player head
        NBT: '{SkullOwner:{Id:"9d58f311-003b-4d1d-8ba8-b678e182bab3",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2MxZGYwZGI4ZDQ3NzNjYzI1NWE2M2I4ZjBiMGU0Y2RkN2Q3NGMzYjRjNjc1MzYyMTY4NDYwYmM2N2JiMzAyZSJ9fX0="}]}}}'
    DOCTOR:
        NAME: '&bDocteur'
        DESC:
        - ''
        - '&8➥ &7Vous avez la possiblité chaque nuit de &eprotéger une personne contre
            les Loup-Garous.'
        - ''
        - '&8➥ &7Votre équipe: &6Village'
        ITEM: apple
    WITCH:
        NAME: '&5Sorcière'
        DESC:
        - ''
        - '&8➥ &7Vous possédez &edeux potions&7. L''une permets de récussiter un joueur,'
        - '&7l''autre permets de tuer un joueur. Vous ne pouvez les utiliser qu''une
            seule fois.'
        - ''
        - '&8➥ &7Votre équipe: &6Village'
        ITEM: player head
        NBT: '{SkullOwner:{Id:"7f92b3d6-5ee0-4ab6-afae-2206b9514a63",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjBlMTNkMTg0NzRmYzk0ZWQ1NWFlYjcwNjk1NjZlNDY4N2Q3NzNkYWMxNmY0YzNmODcyMmZjOTViZjlmMmRmYSJ9fX0="}]}}}'

TEAMS:
    WEREWOLF: '&cLoup-Garou'
    TOWNSFLOK: '&6Village'
    WW_TF: '&6Village &8| &cLoup-Garou'
    SOLO: '&aSolo'

SETUP:
    FORCESTART:
        NAME: '&aDémarrer la partie'
        ITEM: light green dye
        LORE:
        - ''
        - '&8➥ &aForce le démarrage &7de la partie. Waow !'
        - '&7Assurez-vous qu''il y ait suffisamment de joueurs.'
        - ''
    SEPARATOR:
        NAME: ' '
        ITEM: purple stained glass pane
        LORE:
        - ''
    CLOSED:
        NAME: '&cFermer la partie'
        ITEM: red dye
        LORE:
        - ''
        - '&8➥ &cFerme la partie &7aux nouveaux joueurs !'
        - '&7Plus aucun joueur ne pourra rejoindre la partie.'
        - ''
    WHITELIST:
        NAME: '&6Accepter certains joueurs'
        ITEM: orange dye
        LORE:
        - ''
        - '&8➥ &6Accepte uniquement certains joueurs &7que vous aurez désigné.'
        - '&7Pour gérer la liste des joueurs, faites &e/wolfo whitelist&7.'
        - ''
    OPEN:
        NAME: '&aOuvrir la partie à tous'
        ITEM: green dye
        LORE:
        - ''
        - '&8➥ &aOuvre la partie&7 à tous les joueurs !'
        - '&7Idéal pour faire une partie à 27.'
        - ''

GAME:
    DAY: 0
    STATUS: WAIT
    PRIVACY: CLOSED
    SETUP:
        STEP: 0
        FINISHED: false
    LOCATIONS: